version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://bjmp_face_recog:LXKGvyAsIaAx32hT@bjmp.kexnzgt.mongodb.net/bjmp_biometrics?retryWrites=true&w=majority&appName=bjmp

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  python-api:
    build: ./python-api
    container_name: python-api
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://bjmp_face_recog:LXKGvyAsIaAx32hT@bjmp.kexnzgt.mongodb.net/bjmp_biometrics?retryWrites=true&w=majority&appName=bjmp

